name: "🐛 Bug Report"
description: "File a bug to help us improve"
title: "[BUG] <describe issue>"
labels: ["bug"]
assignees: []

body:
  - type: textarea
    id: bug_summary
    attributes:
      label: "🐛 Bug Summary"
      description: "Briefly describe the issue."
      placeholder: "Describe the issue briefly."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "🧪 Steps to Reproduce"
      description: "List the steps to reproduce the bug."
      placeholder: |
        1. Step 1
        2. Step 2
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "✅ Expected Behavior"
      description: "What should happen?"
      placeholder: "The expected outcome of the steps above."
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: "🚫 Actual Behavior"
      description: "What actually happens?"
      placeholder: "The actual outcome of the steps above."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "📸 Screenshots or Logs"
      description: "Attach screenshots or paste error logs here."
      placeholder: "Add any visual aids or logs here."

  - type: input
    id: os
    attributes:
      label: "OS"
      placeholder: "e.g. Windows 11, macOS 13"

  - type: input
    id: browser
    attributes:
      label: "Browser"
      placeholder: "e.g. Chrome 125, Safari 17.2"

  - type: input
    id: version
    attributes:
      label: "App Version"
      placeholder: "e.g. v1.0.0"

  - type: dropdown
    id: environment
    attributes:
      label: "Environment"
      description: "Where did the issue occur?"
      options:
        - Development
        - Staging
        - Production
      multiple: false

  - type: textarea
    id: additional_notes
    attributes:
      label: "📝 Additional Notes"
      description: "Add any other context about the issue here."
