name: "📥 Import Data Request"
description: "Request help importing external data into the project"
title: "[IMPORT DATA] <describe the data>"
labels: ["import", "help wanted"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 📥 Import Data Request

        Use this template to request data that should be imported into the project. Please provide enough detail so others can help.

  - type: input
    id: data-source
    attributes:
      label: "Source of the Data"
      description: "Where is the data located? (URL, file path, API endpoint)"
      placeholder: "e.g. https://example.com/data.json"
    validations:
      required: true

  - type: dropdown
    id: data-format
    attributes:
      label: "Data Format"
      description: "Choose the format of the data to be imported"
      options:
        - CSV
        - JSON
        - XML
        - API (REST)
        - API (GraphQL)
        - Excel
        - Other
    validations:
      required: true

  - type: textarea
    id: structure
    attributes:
      label: "Data Structure / Schema"
      description: "Provide the structure or example of the data. This helps to understand how to process it."
      placeholder: |
        Example:
        ```json
        {
          "id": 1,
          "name": "John",
          "email": "john@example.com"
        }
        ```
    validations:
      required: false

  - type: textarea
    id: destination
    attributes:
      label: "Target Location in Project"
      description: "Where should this data go (e.g., database table, collection, file, etc.)?"
      placeholder: "e.g. Insert into MongoDB collection: users"
    validations:
      required: true

  - type: textarea
    id: transformation
    attributes:
      label: "Data Cleaning / Transformation Needed?"
      description: "Are any changes required to the data before importing?"
      placeholder: "e.g. Remove null emails, convert 'createdAt' to ISO format"
    validations:
      required: false

  - type: dropdown
    id: urgency
    attributes:
      label: "Urgency Level"
      description: "How soon do you need this done?"
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
