blank_issues_enabled: true
contact_links:
  - name: 💬 Ask a Question
    url: https://github.com/AEI-Digital-Co-Ltd/.github/discussions
    about: "Please ask questions in GitHub Discussions instead of issues."
